### ISSUE TITLE
l10n_ca_account_check_writing installation on windows server

### ISSUE THREAD

**Issue by ccobbel** [OCA/l10n-canada#78]
Hi,

Does "l10n_ca_account_check_writing" module is compatible with a windows server?
We installed "num2words" but "l10n_ca_account_check_writing" can be installed because it can not find "num2words". It works fine on linux.
Is there a special step to make it work on windows server?
Thanks a lot for your answer.
Corinne

**Comment by ghost** [comment]
@ccobbel my suggestion would be to run Odoo on a linux vm (debian/ubuntu). Everyone works on linux with Odoo. Community modules tested on Windows are rare.

**Comment by ccobbel** [comment]
I agree, unfortunately my customer choose a windows server so I don't have any choice.
I was just wondering if you knew how to make it work on windows?

**Comment by ghost** [comment]
@ccobbel yes you have a choice, you still can install a linux vm to run Odoo

**Comment by max3903** [comment]
@ccobbel Did you install Odoo Python requirements (libxml, etc) the same way as num2words ?

**Comment by ccobbel** [comment]
Hi Max,

We installed num2words, in addition of the full package python 2.7, is there other dependency than num2words to install?

**Comment by max3903** [comment]
@ccobbel There is no other dependency. The issue seems to be related to where you installed num2words as Odoo cannot find it.

**Comment by ccobbel** [comment]
I was told it was moved under the python 2.7 directory and installed with the setup.py

**Comment by max3903** [comment]
@ccobbel Apparently, it is not sufficient for Odoo to find and use it. If you execute python in the command window and type `import num2words`, do you get an error message ?

**Comment by ghost** [comment]
@ccobbel do you use python virtual_env ?

**Comment by ccobbel** [comment]
Max,

There is a NotimplementedError in /_init_.py line 45, it looks like a language issue (if lang not in CONVERTER_CLASSES:raise NotImplementedError(). I don't now the server language, Odoo is configurated with fr_CA and en_US,I have swiched language in Odoo before updating the list of module but it doesn't change anything.
Is that a known error?

**Comment by max3903** [comment]
@ccobbel fr_CA is not implemented. fr is:
https://github.com/savoirfairelinux/num2words/tree/master/num2words

**Comment by ccobbel** [comment]
ok we will try to implement it.
Thank you very much to both of you

**Comment by max3903** [comment]
@ccobbel Can we close this issue?

**Comment by ccobbel** [comment]
Yes you can close this issue though we have not able to make it work yet.
